name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

defaults:
  run:
    working-directory: balancer-js

jobs:
  build_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: Generate Typechain
        run: npm run typechain:generate
      - name: run rollup build
        run:  npm ci && npm run build
      - name: publish to npm registry
        run: echo $NODE_AUTH_TOKEN && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

env:
  CI: true
